### ISSUE TITLE
Stworzenie warstwy fasad

### ISSUE THREAD

**Issue by cklasicki** [mklasicki/myapp#3]
Warstwa fasad powinna komunikować się bezpośrednio z warstwą prezentacji z kontrolerów. Sprawdź ten wzorzec architektoniczny: 
1. MVC - https://www.tutorialspoint.com/design_pattern/mvc_pattern.htm
2. Facade - https://www.tutorialspoint.com/design_pattern/facade_pattern.htm

**Comment by mklasicki** [comment]
Zrobione
